# Backstage Catalog Info for payment-rest-api
# Place this file in the root of the GitHub repository: vitrina-new/payment-rest-api
# https://backstage.io/docs/features/software-catalog/descriptor-format

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-rest-api
  description: Payment REST API service for payment processing
  title: Payment REST API
  tags:
    - java
    - gradle
    - payments
    - docker
    - spring-boot
    - rest
  annotations:
    # GitHub integration
    github.com/project-slug: vitrina-new/payment-rest-api
    github.com/team-slug: vitrina-new/platform-team

    # TechDocs - enable if you have docs/ folder with mkdocs.yml
    backstage.io/techdocs-ref: dir:.

    # CI/CD badges and links
    github.com/workflows: build.yml,deploy.yml

    # Kubernetes integration (if deployed to K8s)
    backstage.io/kubernetes-id: payment-rest-api
    backstage.io/kubernetes-namespace: payments
    backstage.io/kubernetes-label-selector: app=payment-rest-api

    # SonarQube integration (if applicable)
    sonarqube.org/project-key: vitrina-new_payment-rest-api

    # PagerDuty integration (if applicable)
    pagerduty.com/service-id: PXXXXXX

    # Datadog integration (if applicable)
    datadoghq.com/site: us1.datadoghq.com
    datadoghq.com/dashboard-url: https://app.datadoghq.com/dashboard/xxx

    # Grafana dashboard
    grafana/dashboard-selector: payment-rest-api

    # Jenkins integration (if applicable)
    jenkins.io/job-full-name: payment-platform/payment-rest-api

  links:
    - url: https://github.com/vitrina-new/payment-rest-api
      title: GitHub Repository
      icon: github
    - url: https://github.com/vitrina-new/payment-rest-api/actions
      title: GitHub Actions
      icon: dashboard
    - url: https://api.payments.example.com/swagger-ui
      title: API Documentation (Swagger)
      icon: docs
    - url: https://grafana.example.com/d/payment-api
      title: Grafana Dashboard
      icon: dashboard
    - url: https://confluence.example.com/display/PAY/Payment+REST+API
      title: Confluence Documentation
      icon: docs

spec:
  type: service
  lifecycle: production
  owner: group:platform-team
  system: payment-platform

  # APIs this component provides
  providesApis:
    - payment-rest-api-spec
    - payment-graphql-api

  # APIs this component consumes
  consumesApis:
    - user-authentication-api

  # Dependencies
  dependsOn:
    - resource:payment-database
    - component:fraud-detection-service

---
# API specification for the Payment REST API
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: payment-rest-api-spec
  description: RESTful API for payment transactions, refunds, and payment status management
  title: Payment REST API Specification
  tags:
    - rest
    - openapi
    - payments
    - transactions
  annotations:
    github.com/project-slug: vitrina-new/payment-rest-api
  links:
    - url: https://api.payments.example.com/swagger-ui
      title: Swagger UI
      icon: docs
    - url: https://api.payments.example.com/v3/api-docs
      title: OpenAPI Spec (JSON)
      icon: code

spec:
  type: openapi
  lifecycle: production
  owner: group:platform-team
  system: payment-platform
  definition: |
    openapi: 3.0.3
    info:
      title: Payment REST API
      description: |
        RESTful API for payment processing operations including:
        - Payment initiation and processing
        - Transaction status queries
        - Refund management
        - Payment method management
      version: 2.1.0
      contact:
        name: Platform Team
        email: platform-team@example.com
      license:
        name: Proprietary

    servers:
      - url: https://api.payments.example.com/v2
        description: Production server
      - url: https://api-staging.payments.example.com/v2
        description: Staging server
      - url: http://localhost:8080/v2
        description: Local development

    tags:
      - name: Payments
        description: Payment processing operations
      - name: Transactions
        description: Transaction management
      - name: Refunds
        description: Refund operations

    paths:
      /payments:
        post:
          tags:
            - Payments
          summary: Initiate a new payment
          operationId: createPayment
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/PaymentRequest'
          responses:
            '201':
              description: Payment initiated successfully
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/PaymentResponse'
            '400':
              description: Invalid request
            '401':
              description: Unauthorized
            '422':
              description: Payment validation failed

        get:
          tags:
            - Payments
          summary: List payments
          operationId: listPayments
          parameters:
            - name: status
              in: query
              schema:
                type: string
                enum: [pending, processing, completed, failed, refunded]
            - name: limit
              in: query
              schema:
                type: integer
                default: 20
            - name: offset
              in: query
              schema:
                type: integer
                default: 0
          responses:
            '200':
              description: List of payments
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/PaymentList'

      /payments/{paymentId}:
        get:
          tags:
            - Payments
          summary: Get payment details
          operationId: getPayment
          parameters:
            - name: paymentId
              in: path
              required: true
              schema:
                type: string
                format: uuid
          responses:
            '200':
              description: Payment details
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/PaymentResponse'
            '404':
              description: Payment not found

      /payments/{paymentId}/refund:
        post:
          tags:
            - Refunds
          summary: Initiate a refund
          operationId: createRefund
          parameters:
            - name: paymentId
              in: path
              required: true
              schema:
                type: string
                format: uuid
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/RefundRequest'
          responses:
            '201':
              description: Refund initiated
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/RefundResponse'
            '400':
              description: Invalid request
            '404':
              description: Payment not found

    components:
      schemas:
        PaymentRequest:
          type: object
          required:
            - amount
            - currency
            - paymentMethod
          properties:
            amount:
              type: number
              format: decimal
              minimum: 0.01
              description: Payment amount
            currency:
              type: string
              pattern: '^[A-Z]{3}$'
              example: USD
            paymentMethod:
              type: string
              enum: [card, bank_transfer, wallet]
            customerId:
              type: string
              format: uuid
            metadata:
              type: object
              additionalProperties: true

        PaymentResponse:
          type: object
          properties:
            id:
              type: string
              format: uuid
            status:
              type: string
              enum: [pending, processing, completed, failed, refunded]
            amount:
              type: number
              format: decimal
            currency:
              type: string
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time

        PaymentList:
          type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/PaymentResponse'
            total:
              type: integer
            limit:
              type: integer
            offset:
              type: integer

        RefundRequest:
          type: object
          properties:
            amount:
              type: number
              format: decimal
              description: Partial refund amount (optional, full refund if omitted)
            reason:
              type: string
              maxLength: 500

        RefundResponse:
          type: object
          properties:
            id:
              type: string
              format: uuid
            paymentId:
              type: string
              format: uuid
            amount:
              type: number
              format: decimal
            status:
              type: string
              enum: [pending, processing, completed, failed]
            createdAt:
              type: string
              format: date-time

      securitySchemes:
        bearerAuth:
          type: http
          scheme: bearer
          bearerFormat: JWT

    security:
      - bearerAuth: []
